apiVersion: v1
kind: Service
metadata:
  name: book-manager-api-service
  namespace: book-manager
spec:
  selector:
    app: book-manager-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer